project:
  type: website
  output-dir: _site

website:
  site-url: "https://stephanierod.github.io/"
  navbar:
    background: white
    left:
    - text: "SAR"
      href: index.html
    - text: "Research"  
      href: research.html
    - text: "Teaching"
      href: teaching.html
    - text: "Grants & Awards"
      href: grants.html
    - text: "Community Impact"
      href: community.html
    right:
      - icon: envelope
        href: mailto:stephanie.rodrig@rutgers.edu
      - icon: google-scholar
        href: https://scholar.google.com/citations?user=OWlOVnIAAAAJ&hl=en

  page-footer:
    center: 
      - text: "© 2025 Stephanie A. Rodriguez."
  
format:
  html:
    theme: flatly
    toc: true
    css: styles.css