---
title: "Grants & Awards"
---

## Awards

**2025** — Rutgers University Presidential Award for Excellence in Teaching, Rutgers University, New Brunswick ($1,000)

## Grants and Fellowships

**2025** — The Inclusion, Diversity, Equity, and Advocacy (IDEA) Innovation Grant Program (*Decolonizing Translation in US/Mexico Diaspora*; co-PIs Jennifer Austin and Chantal Fischzang) Rutgers University, Newark ($5,000)

**2025** — 2025 Dean's Travel Fund, Rutgers University, Newark ($868)

**2025** — Cultural Programming Grant (*Food in Translation*; co-PI Taja-Nia Henderson) Rutgers University, Newark ($2,250)

**2024-2025** — Chancellor's Scholars-in-Residence Fellowship, Rutgers University, Newark ($15,000)

**2024-2025** — Mutual Mentoring Team Grant (*If You Build It: Managing Large Scale Events in the Public Humanities Mentoring Network*; co-PIs Jennifer Austin, Lacey Hunter, Maria Kennedy, and Stephanie Rodríguez) ($6,000)

**2022-2025** — Humanities Initiatives at Hispanic-Serving Institutions Grant, National Endowment for the Humanities (*Lives in Translation: Lead Through Language*; co-PIs Jennifer Austin and Jason Cortés) ($150,000)

**2024** — Sheila Y. Oliver Center for Politics and Race in America | Faculty Research (*Decolonizing Translation in US/Mexico Diaspora*; co-PI Janice Gallagher), Rutgers University, Newark ($25,000)

**2024** — Rutgers Global Grant (*Decolonizing Translation in US/Mexico Diaspora*; co-PI Janice Gallagher), Rutgers University, Newark ($5,000)

**2023** — Dean's Travel Fund, Rutgers University, Newark ($500)

**2023** — Open and Affordable Textbooks Program Award, Rutgers University, Newark ($1,000)

**2022** — Open and Affordable Textbooks Program Award, Rutgers University, Newark ($1,000)

---