---
title: "Research"
---

## Overview

My research intersects various topics of translation and language use, focusing on the efficacy, quality, and perception of machine translation, the development of translation pedagogy, and bilingual language development.

## Publications

### Peer-Reviewed Articles

Casillas, J.V., Constantin-Dureci, G., Ráscon Andreu, I., Shao, J., **Rodríguez, S.A.**, Gadamsetty, A., Minetti, A, Laugani, K., Thatcher, J., Gardere, R-T., Taveras, K., Chang, I., Rodríguez, N., Parrish, K. (2025). Opening open science to all: Demystifying reproducibility and transparency practices in linguistic research.

Thane, P. D., Austin, J., **Rodríguez, S. A.**, & Goldin, M. (2025). The acquisition of the Spanish subjunctive by child heritage and L2 learners: evidence from a dual language program. *Studies in Lusophone Linguistics*, 18(3), 193–223. [10.1515/shll-2025-2007](https://doi.org/10.1515/shll-2025-2007)

**Rodríguez, S.A.** (2025). Training of Public Service Interpreters to Serve a Multilingual Population. *Special Issue on Public Service Interpreting*. *International Journal of Language, Translation, and Intercultural Communication*.

Ramirez-Polo, L., **Rodríguez, S. A.**, Blumenfeld, J., Horan, K.M., Merrigan-Robertazzi, M., & Short, J. (2025). Improving Health Equity Through Team Observed Structured Clinical Encounters with LEP Standardized Patients and Healthcare Interpreter Trainees. *Special Issue on Public Service Interpreting*. *International Journal of Language, Translation, and Intercultural Communication*.

Horan, K.M., Blumenfeld, J., Short, J., Merrigan-Robertazzi, M., Ramirez-Polo, L., **Rodríguez, S. A.** (2024). Building Competency in Caring for Patients With Limited English Proficiency: Piloting an Innovative Interprofessional Simulation. *Nurse Educator*.

Austin, J., Thane, P. D., **Rodríguez, S. A.**, & Goldin, M. (2024). The comprehension of clitic gender in child heritage and second language Spanish: Evidence from a dual language program. *Frontiers in Language Sciences*, 3(1334269), 1–15. [https://doi.org/10.3389/flang.2024.1334269](https://doi.org/10.3389/flang.2024.1334269).

### Conference Papers

Jiménez-Crespo, M.A. and **Rodríguez, S.A.** (2025). Is it AI, MT or PE that worry professionals- results from a Human-Centered AI survey. *20th Machine Translation Summit*, Geneva, Switzerland. 09310-2024, 73-87.

Jiménez-Crespo, M.A. and **Rodríguez, S.A.** (2024). Spanish Translation and the Role of Machine Translation and AI Technologies for Public Communication in the United States. *Estudios del Observatorio / Observatorio Studies*, Harvard University, Cambridge, M.A. 09310-2024, 73-87.

### Translation

Ignacio Szmulewicz R., editor; translation, Isidora Ortiz y **Stephanie Rodríguez** (2016); this book includes work from Felipe Baeza Bobadilla, Diego Maureira, Caralina Urtubia, Daniel Opazo, Alejandra Celedón, Carol Illanes, Ignacio Szmulewicz. *Art, City, and the Public Sphere in Chile*, Metales Pesados.

## Presentations

### Conference Presentations

**Rodríguez, S.A.** (2025, September 25-26). The role of language brokers in HCAI in MT: A Critical Review of LLM Use in Public Service Translation. *GLOTECH 2025: Redefining Language Learning and Translation in the Digital Age*. University of Alicante, Spain.

**Rodríguez, S.A.** (2025, September 25). Translation Quality and Error Annotation in Legal Translation: A Comparative Analysis of LLMs and NMT Systems. *The Association for Machine Translation in the Americas*. Virtual.

**Rodríguez, S.A.** (2025, June 30). Investigating the Role of Machine Translation and Large Language Models in Enhancing Language Access. *European Society for Translation Studies*. University of Leeds, Leeds, UK.

Ramirez Polo, L. and **Rodríguez, S.A.** (2025, June 30). A Team Observed Structured Clinical Encounter in A Routine Postpartum Outpatient Visit with Limited English Proficient Patients. *European Society for Translation Studies*. University of Leeds, Leeds, UK.

Jiménez-Crespo, M.A. and **Rodríguez, S.A.** (2025, June 27). Is it AI or PE that worry translation professionals: results from a Human-Centered AI survey. *MT Summit*. Uni Mail, Geneva, Switzerland.

**Rodríguez, S.A.** (2025, June 10). The Role of Language Brokers in Public Service Interpreting: A Training Program Evaluation. *International Symposium on Bilingualism*. Kursaal Congress Centre, San Sebastian, Spain.

**Rodríguez, S.**, Thane, P. D., Austin, J., & Goldin, M. (2025, June 10). On the Role of Heritage Languages in Childhood Trilingualism: Evidence from a Dual Language Program. *International Symposium on Bilingualism*. Kursaal Congress Centre, San Sebastian, Spain.

**Rodríguez, S.A.** (2025, June 9). Examining the Quality and Efficiency of LLMs in Translating Government Documents. *International Symposium on Bilingualism*. Kursaal Congress Centre, San Sebastian, Spain.

Thane, P. D., Austin, J., **Rodríguez, S.**, & Goldin, M. (2025, June 9-13). How do heritage children acquire Spanish in dual language schools? The acquisition of subjunctive mood. *International Symposium on Bilingualism*. Kursaal Congress Centre, San Sebastian, Spain.

**Rodríguez, S.A.** (2025, June 2). Investigating the User Experience: Cognitive Dimensions of Post-Editing LLM-Generated Machine Translations. *Fifth International Conference on Translation, Interpreting and Cognition (ICTIC 5)*. University of Agder, Kristiansand, Norway.

Jiménez-Crespo, M.A. and **Rodríguez, S.A.** (2024, May 31). Spanish translation and the role of language and AI technologies for public communication in the United States. *Observatorio Instituto Cervantes Symposium New Perspectives on Hispanic Cultures*. Harvard University, Cambridge, MA.

Thane, P. D., Austin, J., **Rodríguez, S.**, & Goldin, M. (2024, May 30). How do heritage children acquire Spanish in dual language schools? Charting the acquisition of the subjunctive mood. *Heritage Languages Around the World, 2*. University of Massachusetts Amherst, Amherst, MA.

**Rodríguez, S.A.** (2024, April 7). Advancing Language Access through Technology in Government-Based Settings: Acceptability, Compliance, and Training. *American Translation and Interpreting Studies Association*. Rutgers University, New Brunswick, NJ.

Thane, P. D., Austin, J., **Rodríguez, S.**, & Goldin, M. (2024, March 9). Bilingualism and biliteracy? Supporting partner language development in dual-language immersion. *Multistate Association for Bilingual Education Conference*. Providence, RI.

**Rodriguez, S.**, Thane, P., Austin, J., & Goldin, M. (2024, January 12). Mood changes: charting the development of the Spanish subjunctive in child heritage learners and L2 speakers. *Bilingualism in the Hispanic and Lusophone World*. Puebla, Mexico.

Austin, J., **Rodríguez, S.A.**, & Fischzang, C. (2024, January 5). Lives in Translation at Rutgers University, Newark: Promoting Multilingualism and Social Equity through a Community-Based Translation and Interpreting Program. *Modern Language Association Innovation Room*. Philadelphia, PA.

Chiu, H., Lopez Cruz, A., Chavarria, K., Moreira, R., **Rodríguez, S.A.** (2023, October 25). Interlingual: Volunteers Bridging Language Barriers in Healthcare Settings to Improve Health Equity for LEP Individuals. *VII MOLA Latinx Health Symposium 2023/ IV Medical Spanish Summit*. University of Illinois at Chicago, Chicago, IL.

Gupta, A., Hochbaum, R., Austin, J., **Rodríguez, S.A.**, & Lyon, B. (2021, May 1). Student-based Interpreter Programs that Serve Law School Clinics. 

### Invited Talks

**September 2025** — *he Parent's Playbook: Practical Strategies for Raising Multilingual Children.* MotherEuro. Madrid, Spain.

**May 2025** — *Midwives and Interpreters Working Together: Challenges, Best Practices, and Assessment*. Midwifery Day 2025. NJ Affiliate of the American College of Nurse Midwives. Rutgers University, New Brunswick, NJ.

**February 2025** — *Lives in Translation in the Public Humanities.* SOMOS Poetry and Culture Festival Poetry and Culture in Latin America and Nueva Jersey. Rutgers University, Newark, NJ.

**December 2024** — *Salidas profesionales: ser intérprete y traductor legal en el NJ/NY.* Department of World Languages and Cultures, Rutgers University, Camden, NJ.

**April 2024** — *Community Interpreting in a Healthcare Setting*. School of Nursing, Rutgers University, Newark, NJ.

**December 2023** — *Lives in Translation in the Legal Sector*. School of Criminal Justice, Rutgers University, Newark, NJ.

**November 2023** — *Process of Translation and Use of MT in Literary Texts*. Portuguese Literature in English Translation. Rutgers University, Newark, NJ.

**April 2023** — *Language Access Matters – Court Interpreting*. John Jay College of Criminal Justice, New York, NY.

**March 2023** — *Lives in Translation*. SOMOS Poetry and Culture Festival. Rutgers University, Newark, NJ.

**April 2021** — *What is Medical Interpreting? Increasing Patient Health Outcomes through Language Access*. New Jersey Medical School, Newark, NJ.

**February 2021** — *Bilingual Healthcare Communication and Language Concordance*. New Jersey Medical School, Newark, NJ.


---

*For more information about my research or potential collaborations, please [contact me](mailto:stephanie.rodrig@rutgers.edu).*