---
title: "Teaching"
---

## Courses Developed and Taught

### Rutgers University – Newark, Department of Spanish and Portuguese

**Intro to Translation Studies** (21:940:240)

**Legal Translation & Interpreting** (21:940:360)

**Medical Translation & Interpreting** (21:940:361)

**Translation Technologies** (21:940:358)

**Translation Project Management & Localization** (21:940:359)

**Internship in Translation & Interpreting** (21:940:459)

### Rutgers New Jersey Medical School, Newark

**Medical Student Learning and Training Program – LEP Spanish**  
Summer 2024 and Summer 2025

## Courses Taught

### Rutgers University – New Brunswick, Department of Spanish and Portuguese

**Advanced Composition and Introduction to Translation** (01:940:326)  
Summer 2021 & Summer 2022

**Advanced Translation I** (01:940:401)  
Summer 2023

---

*For information about course offerings or the [Lives in Translation](https://sasn.rutgers.edu/lives-translation) LiT program, please [contact me](mailto:stephanie.rodrig@rutgers.edu).*